apiVersion: v1
kind: Service

metadata:
  name: enterprise-knowledge-ops
  namespace: enterprise-knowledge-ops

spec:
  type: LoadBalancer

  selector:
    app: enterprise-knowledge-ops

  ports:
    - name: streamlit
      protocol: TCP
      port: 8501
      targetPort: 8501